  dockmanProxy:
    profiles: [nostart]
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: dockmanProxy
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
    env_file: ['../.env']
    environment:
      LOG_LEVEL: info # debug,info,notice,warning,err,crit,alert,emerg
      # Base
      PING: 1
      VERSION: 1
      INFO: 1
      EVENTS: 1
      # Ressources nécessaires à Portainer
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      EXEC: 1
      # Opérations d’écriture (création, start/stop, pull, prune…)
      POST: 1
      SYSTEM: 1
      # Contrôles fins LSIO pour lifecycle conteneurs
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
      # Désactivés par défaut (ouvre seulement si tu en as besoin)
      AUTH: 0
      BUILD: 0 # mets à 1 si tu veux construire des images via Portainer
      COMMIT: 0 # mets à 1 si tu « commit » des conteneurs en image
      CONFIGS: 0
      DISTRIBUTION: 0
      NODES: 0
      PLUGINS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      TASKS: 0
      SECRETS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run:rw,uid=${SUID},gid=${GUID},mode=0755
      - /tmp:rw,mode=1777
      - /var/lib/haproxy:rw,uid=${SUID},gid=${GUID},mode=0755
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    user: ${SUID}:${GUID}
    group_add:
      - 990
    networks: [dockmanSocket]
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
